import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { AppBar, Button, ThemeProvider, Toolbar, Typography } from "@mui/material";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import theme from '../src/theme';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ReactIni",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable}`}
      >
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <AppBar 
              position="static" 
              color="primary" 
              sx={{ height: 40, justifyContent: "center" }}>
              <Toolbar 
                sx={{ minHeight: "40px" }}>
                <Typography 
                  variant="h6" 
                  sx={{ flexGrow: 1, marginLeft: 2 }}>
                  ReactIni
                </Typography>
                <Button color="inherit">Login</Button>
              </Toolbar>
            </AppBar>
            {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
